# Input
database:
  import_dir: imports
  data_dir: data
  payment_regex: Download*.CSV
  order_regex: Orders_*.csv
  info_regex: OrdersInfo_*.csv

# Output
output:
  invoice_file: invoices.pdf
  match_dir: build/matches
  rank_dir: build/rankings
  contacts_dir: build/contacts
